# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import amr_pb2 as amr__pb2


class AMRServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.process = channel.unary_unary(
        '/AMRServer/process',
        request_serializer=amr__pb2.AMRInput.SerializeToString,
        response_deserializer=amr__pb2.AMRResponse.FromString,
        )


class AMRServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def process(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AMRServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'process': grpc.unary_unary_rpc_method_handler(
          servicer.process,
          request_deserializer=amr__pb2.AMRInput.FromString,
          response_serializer=amr__pb2.AMRResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'AMRServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
