# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: amr.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='amr.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\tamr.proto\"M\n\x08\x41MRInput\x12%\n\tsentences\x18\x01 \x03(\x0b\x32\x12.AMRInput.Sentence\x1a\x1a\n\x08Sentence\x12\x0e\n\x06tokens\x18\x01 \x03(\t\" \n\x0b\x41MRResponse\x12\x11\n\tamr_parse\x18\x01 \x03(\t21\n\tAMRServer\x12$\n\x07process\x12\t.AMRInput\x1a\x0c.AMRResponse\"\x00\x62\x06proto3'
)




_AMRINPUT_SENTENCE = _descriptor.Descriptor(
  name='Sentence',
  full_name='AMRInput.Sentence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tokens', full_name='AMRInput.Sentence.tokens', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=90,
)

_AMRINPUT = _descriptor.Descriptor(
  name='AMRInput',
  full_name='AMRInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentences', full_name='AMRInput.sentences', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_AMRINPUT_SENTENCE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=90,
)


_AMRRESPONSE = _descriptor.Descriptor(
  name='AMRResponse',
  full_name='AMRResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='amr_parse', full_name='AMRResponse.amr_parse', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=124,
)

_AMRINPUT_SENTENCE.containing_type = _AMRINPUT
_AMRINPUT.fields_by_name['sentences'].message_type = _AMRINPUT_SENTENCE
DESCRIPTOR.message_types_by_name['AMRInput'] = _AMRINPUT
DESCRIPTOR.message_types_by_name['AMRResponse'] = _AMRRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AMRInput = _reflection.GeneratedProtocolMessageType('AMRInput', (_message.Message,), {

  'Sentence' : _reflection.GeneratedProtocolMessageType('Sentence', (_message.Message,), {
    'DESCRIPTOR' : _AMRINPUT_SENTENCE,
    '__module__' : 'amr_pb2'
    # @@protoc_insertion_point(class_scope:AMRInput.Sentence)
    })
  ,
  'DESCRIPTOR' : _AMRINPUT,
  '__module__' : 'amr_pb2'
  # @@protoc_insertion_point(class_scope:AMRInput)
  })
_sym_db.RegisterMessage(AMRInput)
_sym_db.RegisterMessage(AMRInput.Sentence)

AMRResponse = _reflection.GeneratedProtocolMessageType('AMRResponse', (_message.Message,), {
  'DESCRIPTOR' : _AMRRESPONSE,
  '__module__' : 'amr_pb2'
  # @@protoc_insertion_point(class_scope:AMRResponse)
  })
_sym_db.RegisterMessage(AMRResponse)



_AMRSERVER = _descriptor.ServiceDescriptor(
  name='AMRServer',
  full_name='AMRServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=126,
  serialized_end=175,
  methods=[
  _descriptor.MethodDescriptor(
    name='process',
    full_name='AMRServer.process',
    index=0,
    containing_service=None,
    input_type=_AMRINPUT,
    output_type=_AMRRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AMRSERVER)

DESCRIPTOR.services_by_name['AMRServer'] = _AMRSERVER

# @@protoc_insertion_point(module_scope)
