channels:
  - defaults
  - https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda
  - powerai

dependencies:
#
# for python 3.7 remove version from pytorch and apex
  - requests
#
# fairseq
  - cffi
  - fastBPE
  - regex
  - sacrebleu
#
# transition_amr_parser
  - pytorch=1.2
  #- cudatoolkit=10.1.168=533.g8d035fd
  - apex
  - h5py
  - tqdm
#    
# debug/optimization
  - line_profiler

# The version available wont be as high as the x86 one
  - spacy
